# Generated by Django 4.2.5 on 2023-09-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='non-cash', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
