# Generated by Django 4.2.5 on 2023-10-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_cours_price_lesson_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='summ',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
